export const ICON_NAMES = [
  'BadgeCheck',
  'Ban',
  'BookOpen',
  'Bot',
  'Braces',
  'CircleStop',
  'CloudDownload',
  'Code',
  'Combine',
  'Copy',
  'Database',
  'FileInput',
  'FileOutput',
  'FileSearch',
  'FileText',
  'FileUp',
  'Files',
  'Filter',
  'GitBranch',
  'GitFork',
  'GitMerge',
  'Globe',
  'History',
  'KeyRound',
  'Layers',
  'Library',
  'List',
  'Mail',
  'MessageSquare',
  'MessagesSquare',
  'Pause',
  'PenLine',
  'Pin',
  'Play',
  'Plug',
  'Puzzle',
  'Radio',
  'RefreshCw',
  'Repeat',
  'RotateCcw',
  'Search',
  'Send',
  'Settings',
  'Share2',
  'Shuffle',
  'Sparkles',
  'Split',
  'StickyNote',
  'TextCursorInput',
  'Timer',
  'Trash2',
  'Type',
  'Upload',
  'User',
  'Variable',
  'Webhook',
  'Workflow'
] as const

export type IconName = (typeof ICON_NAMES)[number]

export const ICON_NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES)
